services:
  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGODB_ROOT_PASSWORD=P@ssw0rd
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'

  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: npm run start:dev gateway
    env_file:
      - ./apps/gateway/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  orders:
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    command: npm run start:dev orders
    env_file:
      - ./apps/orders/.env
    depends_on:
      - mongodb
      - gateway
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
volumes:
  mongodb_master_data:
